USE `biblioteca`;
DROP function IF EXISTS `fun_prest`;

DELIMITER $$
USE `biblioteca`$$
CREATE FUNCTION `fun_prest` (can_prest INT)
RETURNS INTEGER
BEGIN
 IF can_prest <= 2 THEN 
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'PRESTAMO APROBADO';
		ELSE 
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'PRESTAMO DESAPROBADO';
    END IF;
RETURN 1;
END$$

DELIMITER ;


